/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package casinilorenzoprogettothreadsbasket;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author loren
 */
public class JFrmBet extends javax.swing.JFrame {

    private java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrmBet.class.getName());
    private String[] Concorrente = {"Concorrente 1", "Concorrente B", "Concorrente C", "Concorrente D"};
    private double[] Quote = {3.5, 2.0, 1.5, 1.2};

    /**
     * Creates new form JFrmBet
     */
    public JFrmBet() {
        initComponents();
        setupBet();
    }

    private void setupBet() {
        GameState gs = GameState.getInstance();
        String[] items = new String[4];
        for (int i = 0; i < 4; i++) {
            String nome = gs.getNomiGiocatori()[i];
            int forza = gs.getForzaGiocatori()[i];
            if (forza <= 0) {
                forza = 5;
            }
            double quota = Math.round((1.2 + (10 - forza) * 0.42) * 10.0) / 10.0;
            items[i] = nome + "  [" + quota + "x]";
        }
        jComboBox1.setModel(new DefaultComboBoxModel<>(items));
        jTextArea1.setEditable(false);
        jTextArea1.setText("Seleziona giocatore e importo, poi Conferma.");
        if (gs.isGaraCompletata() && gs.hasScommessa()) {
            mostraRisultato();
        }
    }

    private void confermaScommessa() {
        try {
            double importo = Double.parseDouble(jTextField1.getText().trim());
            if (importo <= 0) {
                jTextArea1.setText("Importo deve essere > 0.");
                return;
            }
            int idx = jComboBox1.getSelectedIndex();
            GameState gs = GameState.getInstance();
            String nome = gs.getNomiGiocatori()[idx];
            int forza = gs.getForzaGiocatori()[idx];
            double quota = Math.round((1.2 + (10 - forza) * 0.42) * 10.0) / 10.0;
            gs.setSquadraScelta(nome);
            gs.setImportoBet(importo);
            gs.setQuotaBet(quota);
            jTextArea1.setText("✅ Scommessa su: " + nome+ "\nImporto: €" + String.format("%.2f", importo)+ "\nQuota: " + quota + "x"+ "\nVincita potenziale: €" + String.format("%.2f", importo * quota));
            if (gs.isGaraCompletata()) {
                mostraRisultato();
            }
        } catch (NumberFormatException ex) {
            jTextArea1.setText("Errore: inserisci un numero valido.");
        }
    }

    private void mostraRisultato() {
        GameState gs = GameState.getInstance();
        String v = gs.getVincitoreGara();
        String s = gs.getSquadraScelta();
        double importo = gs.getImportoBet();
        double quota = gs.getQuotaBet();
        if (s != null && s.equals(v)) {
            jLabel3.setText("🏆 VINTO! +€" + String.format("%.2f", importo * quota));
        } else {
            jLabel3.setText("❌ PERSO -€" + String.format("%.2f", importo) + " | Vince: " + v);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BtnScommetti = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        BtnInizio = new javax.swing.JButton();
        BtnGara = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("BET");

        jLabel2.setText("Importo");

        BtnScommetti.setText("Scommetti");
        BtnScommetti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnScommettiActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Vincita");

        BtnInizio.setText("Inizio");
        BtnInizio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInizioActionPerformed(evt);
            }
        });

        BtnGara.setText("Gara");
        BtnGara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGaraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(BtnScommetti))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel3)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnGara)
                .addGap(21, 21, 21)
                .addComponent(BtnInizio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnInizio)
                        .addComponent(BtnGara)))
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnScommetti)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGaraActionPerformed
        // TODO add your handling code here:
        new JFrmGara().setVisible(true); 
        dispose();
    }//GEN-LAST:event_BtnGaraActionPerformed

    private void BtnInizioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInizioActionPerformed
        // TODO add your handling code here:
        new JFrmInizio().setVisible(true); 
        dispose();
    }//GEN-LAST:event_BtnInizioActionPerformed

    private void BtnScommettiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnScommettiActionPerformed
        // TODO add your handling code here:
        confermaScommessa();
    }//GEN-LAST:event_BtnScommettiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGara;
    private javax.swing.JButton BtnInizio;
    private javax.swing.JButton BtnScommetti;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
